name: openai-batch-test

type: python

env:
  OPENAI_BASE_URL: https://proxy-shopify-ai.local.shop.dev/v1
  # OPENAI_BASE_URL: http://proxy-shopify-ai.local.shop.dev/vendors/azureopenai-eastus/openai

up:
  - python: 3.11.13
  - uv
  - uv_tools:
      - ruff

commands:
  test-openai: python batch_processor.py process sample_batch_input.jsonl
  test-azure: python batch_processor.py process azure_batch_input.jsonl

check:
  style: /opt/dev/bin/dev style
