name: openai-batch-test

type: python

env:
  OPENAI_BASE_URL: https://proxy-shopify-ai.local.shop.dev/v1
  # OPENAI_BASE_URL: http://proxy-shopify-ai.local.shop.dev/vendors/azureopenai-eastus/openai

up:
  - python: 3.11.13
  - uv
  - uv_tools:
      - ruff

check:
  style: /opt/dev/bin/dev style
